### ISSUE TITLE
关于pyspark

### ISSUE THREAD

**Issue by ajoeajoe** [Kesci/klab-kernel#43]
有pyspark的安装计划吗

**Comment by ajoeajoe** [comment]
!pip install pyspark  已安装

**Comment by ggaaooppeenngg** [comment]
@ajoeajoe  具体有啥需求么，这个只是客户端吧，您使用场景是什么？

**Comment by ajoeajoe** [comment]
想问下你们平台应该是定位实验性数据的分析挖掘，不能上传加载大数据，能跑多大数据，什么时候可以连接数据库

**Comment by ajoeajoe** [comment]
@ggaaooppeenngg 想问下你们平台应该是定位实验性数据的分析挖掘，不能上传加载大数据，能跑多大数据，什么时候可以连接数据库

**Comment by ggaaooppeenngg** [comment]
@ajoeajoe 这个我们考虑过做，但是要和具体的生产环境做集成才行，我们自己提供一套大数据的服务也不是不可能，要不我加一下微信聊聊应用场景？我的微信是 qwe383538557
