### ISSUE TITLE
原装mxnet1.1运行d2l课程脚本报错

### ISSUE THREAD

**Issue by zhoujuncsu** [Kesci/klab-kernel#93]
/opt/conda/lib/python3.6/site-packages/mxnet/base.py in check_call(ret)
    144     """
    145     if ret != 0:
--> 146         raise MXNetError(py_str(_LIB.MXGetLastError()))
    147 
    148 

MXNetError: [10:27:25] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/./any.h:286: Check failed: type_ != nullptr The any container is empty requested=N5mxnet10Imperative6AGInfoE

Stack trace returned 10 entries:
[bt] (0) /opt/conda/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x192112) [0x7f8c1e7ab112]
[bt] (1) /opt/conda/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x192738) [0x7f8c1e7ab738]
[bt] (2) /opt/conda/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x237ae9c) [0x7f8c20993e9c]
[bt] (3) /opt/conda/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x239044e) [0x7f8c209a944e]
[bt] (4) /opt/conda/lib/python3.6/site-packages/mxnet/libmxnet.so(MXAutogradBackwardEx+0x527) [0x7f8c208e6227]
[bt] (5) /opt/conda/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7f8c4b81cec0]
[bt] (6) /opt/conda/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7f8c4b81c87d]
[bt] (7) /opt/conda/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f8c4ba31dee]
[bt] (8) /opt/conda/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12825) [0x7f8c4ba32825]
[bt] (9) /opt/conda/bin/python(_PyObject_FastCallDict+0x8b) [0x562d499971bb]

**Comment by ggaaooppeenngg** [comment]
`!pip install -i  https://pypi.doubanio.com/simple/  --trusted-host pypi.doubanio.com  mxnet==1.5.0b20190222` 升级 mxnet 解决，之前 mxnet 版本本身更新的比较慢，和我们大多数的库都不太兼容所以一直没更新。
